-- # Monkey D. Luffy
-- ---------------------------------------------------------------
DO $$
DECLARE _series_id int8;
BEGIN

_series_id := (select id from master.series where code = 'OP01');

insert into master.character_summary (character_id,location_id,introduction,history,abilities)
values ((select id from master.character where alias = 'Luffy'),
        (select id from master.location where code = 'OPLC03'),
        'Monkey D. Luffy, also known as "Straw Hat Luffy" and commonly as "Straw Hat", is the main protagonist of the manga and anime, One Piece. He is the founder and captain of the increasingly infamous and powerful Straw Hat Pirates, as well as one of its top fighters. His lifelong dream is to become the Pirate King by finding the legendary treasure left behind by the late Gol D. Roger. He believes that being the Pirate King means having the most freedom in the world.\nBorn in Foosha Village, Luffy accidentally ate the Gomu Gomu no Mi at age 7, which turned his body into rubber. He met "Red-Haired" Shanks, who gave Luffy the very Straw Hat that has become Luffy''s signature accessory, having gifted it to the boy as part of a promise for them to meet again someday. Luffy is the son of the Revolutionary leader Monkey D. Dragon, the grandson of the Marine hero Monkey D. Garp, the sworn brother of the late "Fire Fist" Portgas D. Ace and Revolutionary Chief-of-Staff Sabo, and the foster son of Curly Dadan. He is one of the few people in the world who carries the Will of D.\nLuffy has gone up against numerous global powers around him, starting with fighting the most powerful pirates in the East Blue and moving to clashes against the Marines, Seven Warlords of the Sea, Cipher Pol, World Nobles, and even the Four Emperors of the Grand Line, emerging victorious in a majority of these battles. He invaded and indirectly caused the annihilation of Enies Lobby, escaped the impregnable Impel Down, and was a focal figure in the Summit War of Marineford. He either defeated or befriended seven of the eleven known past or present Warlords prior to the organization''s dissolution, and has invaded the territory of two Emperors. Luffy''s accomplishments and heritage have caused him to be labeled as a "Dangerous Future Element" while in the process gaining a reputation for being "reckless" and, in some cases, "insane", earning the wrath of Fleet Admiral Sakazuki, the Marine Headquarters, and even the World Government.\nLuffy also has a penchant for attracting followers and has unwillingly been named the leader of the Straw Hat Grand Fleet, consisting of seven pirate crews who swore to come to his aid whenever he wishes. After learning of this and his exploits against the Big Mom Pirates, the press has labeled him the "Fifth Emperor of the Sea", though many prominent figures consider this to be exaggerated.',
        'Luffy was born in Foosha Village to Monkey D. Dragon and an unknown woman. Dragon left Luffy in the care of his grandfather, Monkey D. Garp, who did many dangerous things to Luffy to make him stronger, like throwing him down a deep ravine, leaving him alone in the wild, and tying him to a balloon.\nWhen Luffy was 6, Shanks and the Red Hair Pirates stationed themselves in Foosha Village. While they were there, their sniper Yasopp frequently told Luffy that he had a son his age named Usopp.Luffy wanted to join the Red Hair Pirates, and after they had been in the village for nearly a year, he stabbed himself under his left eye to prove he was tough enough to be a pirate.\n After the Red Hair Pirates left, Garp took Luffy to Mt. Colubo and placed him in the care of the mountain bandit Curly Dadan and the Dadan Family. He introduced Luffy to Dadan''s other ward Portgas D. Ace, but Ace was cold toward Luffy.Every day, Ace would travel away from the Dadan Family hideout, and Luffy attempted to follow him. Ace would put obstacles in his path to stop him, but Luffy continued following him.\nEventually, Luffy made it to Gray Terminal, where he found Ace counting money with a boy named Sabo. When Luffy went up to them, Ace and Sabo captured him and talked about killing him to keep their secret safe. Porchemy of the Bluejam Pirates then came walking through the woods, and as Ace and Sabo hid from him, they left Luffy to be captured. Porchemy took Luffy to his base and interrogated him about the money Ace and Sabo had stolen from his crew. Luffy refused to answer him, even when Porchemy nearly beat him to death with spiked gloves.Ace and Sabo then came to the base and freed Luffy, with Ace beating Porchemy.After this incident, Luffy, Ace, and Sabo became friends and went on many adventures together, becoming known throughout the Goa Kingdom.\nLater, Ace that Sabo had been killed by a World Noble while setting out to sea, leaving them devastated. Luffy went to the coast and cried all night, and Ace came to him the next morning.Luffy made Ace promise that he would not die, swearing to become stronger. For the next seven years, the two continued adventuring and training to get stronger, with Luffy learning to throw effective long-range punches with his stretching. A 14-year-old Luffy then bid farewell to Ace, who sailed out to sea as a pirate upon turning 17. Three more years passed before Luffy became a pirate himself, and he bid farewell to the Dadan Family before going to Foosha Village to say goodbye and set sail. When the Lord of the Coast emerged to confront him, Luffy punched it away with Gomu Gomu no Pistol. As he sailed, Luffy plotted to recruit ten crewmates, get a Jolly Roger, and become the Pirate King.',
        'Despite his relatively small physical stature compared to most of the world''s powerful fighters, Luffy has developed significant physical strength to match them. His grandfather Garp used harsh and unorthodox training methods to make him grow stronger, such as leaving him alone in the wilderness as a young child, making him fight monkeys, tying him to balloons so he would float away, or throwing him into a bottomless pit, as well as several years of further rigorous training in the extremely harsh environment in Mt. Colubo and Rusukaina. A notable example of this strength was on Dressrosa when he used his foot to block a stomp by Donquixote Doflamingo, a man nearly twice his height with immense physical power of his own, without any leverage. Earlier that day, he had effortlessly flipped over the massive gladiator Spartan, defeating him. In Skypiea, he was capable of moving around during his fight against Enel despite having a massive golden ball molded around his hand, and even climbed up a massive beanstalk with it.  When caught between two large brick buildings in Water 7, he was eventually able to push them apart to free himself.Even in a severely weakened state after his calamitous battle at Marineford, Luffy was still able to cause massive destruction on Amazon Lily and lift a boulder several times larger than himself with enough force to destroy a nearby rock formation.\nLuffy has utilized his Devil Fruit Gears to tremendously increase his physical strength and subdue powerful opponents like Blueno, Rob Lucci, and Donquixote Doflamingo. He took out a member of the Marines'' Giant Squad with a single Gear 3 punch, and two years later, he defeated the powerful giant Hajrudin with a single Gear 2 punch to the face. On Fish-Man Island, the Sea Kings believed he would have completely destroyed the gigantic ship Noah before it would have landed had they not stopped him.\nWhen he was imprisoned in Wano Country, he wore Seastone handcuffs that significantly weakened him and prevented him from using his Devil Fruit powers, and he exploited his prison labor as a new training method to get stronger in his weakened state, being able to lift and carry hundreds of blocks several times his size, and a few days later was able to break through the helmet of the vice warden Daifugo and injure him with a simple kick.'
        );

insert into master.category_image (code,"name")
values ('OPIC003','character-detail-luffy');

insert into master.image (series_id, category_id, code, filename) values
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-01.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-02.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-03.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-04.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-05.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-06.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-07.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-08.jpg'),
(_series_id, (select id from master.category_image where code = 'OPIC003'), 'luffy-gallery','luffy-gallery-09.jpg');

insert into master.character_gallery (character_id, image_id)
select c.id, i.id from master.character c, master.image i where c.name like '%Luffy%' and i.code = 'luffy-gallery';

insert into master.character_tag (character_id,tag_id) values
((select id from master.character where alias = 'Luffy'), (select id from master.tag where code = 'OPTG034')),
((select id from master.character where alias = 'Luffy'), (select id from master.tag where code = 'OPTG010')),
((select id from master.character where alias = 'Luffy'), (select id from master.tag where code = 'OPTG030')),
((select id from master.character where alias = 'Luffy'), (select id from master.tag where code = 'OPTG051')),
((select id from master.character where alias = 'Luffy'), (select id from master.tag where code = 'OPTG037')),
((select id from master.character where alias = 'Luffy'), (select id from master.tag where code = 'OPTG062')),
((select id from master.character where alias = 'Luffy'), (select id from master.tag where code = 'OPTG060'));

insert into master.character_relationship (relationship_id,relationship_character_id, character_id) values
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Zoro%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Sanji%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Nami%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Chopper%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Usopp%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Franky%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Robin%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'OPRS01'),(select id from master.character where name like '%Jinbe%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'GERS02'),(select id from master.character where name like '%Portgas%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'GERS03'),(select id from master.character where name like '%Garp%'),(select id from master.character where alias = 'Luffy')),
((select id from master.relationship where code = 'GERS01'),(select id from master.character where name like '%Dragon%'),(select id from master.character where alias = 'Luffy'));

END $$;
